### ISSUE TITLE
Retard

### ISSUE THREAD

**Issue by ghost** [xuviuos/simple-growtopia-bot-fixed-by-xuviuos#1]
retard i made this project where is credits???

**Comment by xuviuos** [comment]
why do you cry, i used givesae github source idc who made it just fixed it thats all "retard"

**Comment by xuviuos** [comment]
> retard i made this project where is credits???

why do you cry, i used givesae github source idc who made it, i just fixed it thats all "retard"

**Comment by ghost** [comment]
> > retard i made this project where is credits???
> 
> why do you cry, i used givesae github source idc who made it, i just fixed it thats all "retard"
 
now ?

![20211229_161859](https://user-images.githubusercontent.com/83706783/147666480-173c9cc4-4588-4909-a65e-3b8e2cab72bb.jpg)

**Comment by xuviuos** [comment]
> 

cant u read? I just said idc who made it i fixed givesae project
